[package]
name = "rs"
version = "0.1.0"
authors = ["Orlyn Gerano <orlyn_gerano@yahoo.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
lazy_static = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"